language: java

before_install: 
  - if [ ! -d "$HOME/.m2" ]; then mkdir .m2 ; fi
  - cp ci/settings.xml $HOME/.m2/settings.xml

script: mvn -f beanstalk-maven-plugin-it/pom.xml clean verify -Dbeanstalk.project.name=mbit-travis -Prelease,it

jdk:
- openjdk7

env:
  global:
  - secure: uz02og5+IWdVl2C0XzATR/9ZdKCLhRVeUS7CmnFDQQF5wwMhhm377QinnLFsXIMI+W+DVuHb8ooq9sD0odji6ztH5YUcYmYKqD3QBpo3o70IIFWwBF5geiFJ3XHrKdfIUZ+7ihifAGitkL3j+qPNZm/xHqVqRzLaOzEF2akT44w=
  - secure: qGMwNeZZ7ECzUwqU0G8UO9FNIE5faXfXBaTZ+sYTGm+WhpJl8SC92BQsFjaJAQeVwFU2WeM/7DtwMu9wzhtnfzPvAIaHKgdLvl3acGyhG5Npu0TuhSd/BNlPQ6XTjmrS+KT5OVNJB4GhwniDhk2h7vMtuDIqCWQmQvY7ODcOa8g=
  - EC2_KEY_NAME=aldrin@leal.eng.br AWSEB_S3_BUCKET=ingenieux-beanstalk-apps
